sudo: required
dist: xenial
services:
  - docker
python: 3.8
language: python
cache: pip
service:
  - docker

before_install:
  - docker build -t produc -f Dockerfile .

install:
  - pip install docker-compose --upgrade

test:
  script:
    - sudo apt-get update -qy
    - sudo apt-get install -y ruby-dev
    - sudo gem install dpl --pre
    - sudo gem install bundler
    - sudo gem install faraday-net_http -v 2.1.0
    - yarn install

script:
  - docker-compose run web python manage.py test

after_failure:
  - docker-compose logs

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  on:
    branch: main
